# -*- coding: utf-8 -*-
"""
楼栋楼层平面布局配置
从Excel布局图(A塔13楼_12楼_B塔13楼_12楼房间布局图)提取，2026-08-24
A塔12/13楼共用布局，B塔12/13楼共用布局（上下楼位置一一对应）
未录入系统的房间位置显示为"预留"，未来添加房间后自动点亮
"""

LAYOUTS = {
    'A': {
        'rows': 17,
        'cols': 14,
        'cells': [
            {'row': 1, 'col': 1, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '24'},
            {'row': 1, 'col': 3, 'rowspan': 1, 'colspan': 10, 'type': 'corridor', 'label': '走廊'},
            {'row': 1, 'col': 14, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '33'},
            {'row': 2, 'col': 3, 'rowspan': 2, 'colspan': 1, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 2, 'col': 12, 'rowspan': 2, 'colspan': 1, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 3, 'col': 1, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '23'},
            {'row': 3, 'col': 14, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '34'},
            {'row': 4, 'col': 3, 'rowspan': 2, 'colspan': 1, 'type': 'function', 'label': '功能间'},
            {'row': 4, 'col': 4, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '25'},
            {'row': 4, 'col': 5, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '26'},
            {'row': 4, 'col': 6, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '27'},
            {'row': 4, 'col': 7, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '28'},
            {'row': 4, 'col': 8, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '29'},
            {'row': 4, 'col': 9, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '30'},
            {'row': 4, 'col': 10, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '31'},
            {'row': 4, 'col': 11, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '32'},
            {'row': 4, 'col': 12, 'rowspan': 2, 'colspan': 1, 'type': 'function', 'label': '功能间'},
            {'row': 5, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '22'},
            {'row': 5, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '35'},
            {'row': 6, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '21'},
            {'row': 6, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '36'},
            {'row': 7, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '19'},
            {'row': 7, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '20'},
            {'row': 7, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '38'},
            {'row': 7, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '37'},
            {'row': 8, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '17'},
            {'row': 8, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '18'},
            {'row': 8, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '40'},
            {'row': 8, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '39'},
            {'row': 9, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '15'},
            {'row': 9, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '16'},
            {'row': 9, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '42'},
            {'row': 9, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '41'},
            {'row': 10, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '13'},
            {'row': 10, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '14'},
            {'row': 10, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '44'},
            {'row': 10, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '43'},
            {'row': 11, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '11'},
            {'row': 11, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '12'},
            {'row': 11, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '46'},
            {'row': 11, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '45'},
            {'row': 12, 'col': 1, 'rowspan': 2, 'colspan': 1, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 12, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '10'},
            {'row': 12, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '47'},
            {'row': 12, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 13, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '09'},
            {'row': 13, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '48'},
            {'row': 13, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '49'},
            {'row': 14, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '07'},
            {'row': 14, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '08'},
            {'row': 14, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '50'},
            {'row': 14, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '51'},
            {'row': 15, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '05'},
            {'row': 15, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '06'},
            {'row': 15, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '52'},
            {'row': 15, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '53'},
            {'row': 16, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '03'},
            {'row': 16, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '04'},
            {'row': 16, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '54'},
            {'row': 16, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '55'},
            {'row': 17, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '01'},
            {'row': 17, 'col': 3, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '02'},
            {'row': 17, 'col': 12, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '56'},
            {'row': 17, 'col': 14, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '57'},
        ]
    },
    'B': {
        'rows': 20,
        'cols': 16,
        'cells': [
            {'row': 1, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '28'},
            {'row': 1, 'col': 3, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '29'},
            {'row': 1, 'col': 4, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '30'},
            {'row': 1, 'col': 5, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '31'},
            {'row': 1, 'col': 6, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '33'},
            {'row': 1, 'col': 8, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '37'},
            {'row': 1, 'col': 9, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '39'},
            {'row': 1, 'col': 10, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '41'},
            {'row': 1, 'col': 11, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '43'},
            {'row': 1, 'col': 12, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '45'},
            {'row': 1, 'col': 13, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '46'},
            {'row': 1, 'col': 14, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '47'},
            {'row': 1, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '48'},
            {'row': 2, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '27'},
            {'row': 2, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '49'},
            {'row': 3, 'col': 1, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '26'},
            {'row': 3, 'col': 16, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '50'},
            {'row': 4, 'col': 3, 'rowspan': 1, 'colspan': 12, 'type': 'corridor', 'label': '走廊/楼梯间'},
            {'row': 5, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '25'},
            {'row': 5, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 5, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 5, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '51'},
            {'row': 6, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '24'},
            {'row': 6, 'col': 3, 'rowspan': 2, 'colspan': 2, 'type': 'function', 'label': '功能间'},
            {'row': 6, 'col': 5, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '32'},
            {'row': 6, 'col': 6, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '34'},
            {'row': 6, 'col': 7, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '35'},
            {'row': 6, 'col': 8, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '36'},
            {'row': 6, 'col': 9, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '38'},
            {'row': 6, 'col': 10, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '40'},
            {'row': 6, 'col': 11, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '42'},
            {'row': 6, 'col': 12, 'rowspan': 3, 'colspan': 1, 'type': 'room', 'suffix': '44'},
            {'row': 6, 'col': 13, 'rowspan': 3, 'colspan': 2, 'type': 'function', 'label': '功能间'},
            {'row': 6, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '52'},
            {'row': 7, 'col': 1, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '23'},
            {'row': 7, 'col': 16, 'rowspan': 2, 'colspan': 1, 'type': 'room', 'suffix': '53'},
            {'row': 9, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '22'},
            {'row': 9, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '54'},
            {'row': 10, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '21'},
            {'row': 10, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '20'},
            {'row': 10, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '56'},
            {'row': 10, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '55'},
            {'row': 11, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '19'},
            {'row': 11, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '18'},
            {'row': 11, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '58'},
            {'row': 11, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '57'},
            {'row': 12, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '17'},
            {'row': 12, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '16'},
            {'row': 12, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '60'},
            {'row': 12, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '59'},
            {'row': 13, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '15'},
            {'row': 13, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '14'},
            {'row': 13, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '62'},
            {'row': 13, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '61'},
            {'row': 14, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '13'},
            {'row': 14, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '12'},
            {'row': 14, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '64'},
            {'row': 14, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '63'},
            {'row': 15, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 15, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '11'},
            {'row': 15, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '65'},
            {'row': 15, 'col': 16, 'rowspan': 2, 'colspan': 1, 'type': 'stairs', 'label': '楼梯间'},
            {'row': 16, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '09'},
            {'row': 16, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '10'},
            {'row': 16, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '66'},
            {'row': 17, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '07'},
            {'row': 17, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '08'},
            {'row': 17, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '68'},
            {'row': 17, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '67'},
            {'row': 18, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '05'},
            {'row': 18, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '06'},
            {'row': 18, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '70'},
            {'row': 18, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '69'},
            {'row': 19, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '03'},
            {'row': 19, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '04'},
            {'row': 19, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '72'},
            {'row': 19, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '71'},
            {'row': 20, 'col': 1, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '01'},
            {'row': 20, 'col': 3, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '02'},
            {'row': 20, 'col': 13, 'rowspan': 1, 'colspan': 2, 'type': 'room', 'suffix': '74'},
            {'row': 20, 'col': 16, 'rowspan': 1, 'colspan': 1, 'type': 'room', 'suffix': '73'},
        ]
    },
}


def detect_tower(rooms):
    """从房间号列表判断楼栋塔号(A/B)"""
    for room in rooms:
        rn = room.room_number or ''
        if len(rn) >= 1 and rn[0] in ('A', 'B'):
            return rn[0]
    return None


def get_layout(tower):
    """获取塔的布局配置"""
    return LAYOUTS.get(tower)